services:  
  api:
    image: 079829475258.dkr.ecr.us-east-1.amazonaws.com/spaced-repetition-api
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: ecto://postgres:postgres@db:5432/spaced_repetition
      PORT: 8000
  
  auth:
    depends_on: 
     - db
    image: 079829475258.dkr.ecr.us-east-1.amazonaws.com/spaced-repetition-user-management
    ports: 
      - 4000:4000
    env_file:
      - .env.dev
    environment:
      APP_ENDPOINT: http://api:8000
      REDIS_HOST: cache

  cache:
    image: redis
    ports:
      - 6379:6379

  db: 
    image: postgres:14.7
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - .env.dev