# @format

name: Spaced Repetition App
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 1-signup
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.17.x'
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.17.x'
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          AWS_REGION: ${{secrets.REGION}}   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
  # Dockerize:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - name: Install packages
  #       run: npm install
  #     - name: Build
  #       run: npm run build --if-present
  #     ## Added this step per recommendation in docs
  #     ## https://github.com/marketplace/actions/build-and-push-docker-images
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./Dockerfile.prod
  #         push: true
  #         tags: aeissa/spaced-repetition-app
      
